export const users = [
  {
    name: "Dima",
    email: "dima@gmail.com",
    gender: "male",
    birthday: "16.11.2006",
    age: 25,
    position: "UI/UX Designer",
    role: "Middle",
  },
  {
    name: "Anna Petrova",
    email: "anna.petrova@example.com",
    gender: "female",
    birthday: "03.04.1998",
    age: 26,
    position: "Frontend Developer",
    role: "Junior",
  },
  {
    name: "Ivan Sidorov",
    email: "ivan.sid@example.com",
    gender: "male",
    birthday: "22.09.1995",
    age: 29,
    position: "Backend Developer",
    role: "Senior",
  },
  {
    name: "Maria Volkova",
    email: "m.volkova@example.com",
    gender: "female",
    birthday: "11.01.2001",
    age: 23,
    position: "QA Engineer",
    role: "Middle",
  },
  {
    name: "Artem Koval",
    email: "artem.kov@example.com",
    gender: "male",
    birthday: "27.07.1999",
    age: 25,
    position: "Product Manager",
    role: "Middle",
  },
  {
    name: "Sofia Belaya",
    email: "sofia.belaya@example.com",
    gender: "female",
    birthday: "10.10.1997",
    age: 27,
    position: "Graphic Designer",
    role: "Senior",
  },
  {
    name: "Maksim Lebedev",
    email: "maks.lebedev@example.com",
    gender: "male",
    birthday: "18.02.1996",
    age: 28,
    position: "DevOps Engineer",
    role: "Middle",
  },
  {
    name: "Valeria Karpova",
    email: "valeria.karpova@example.com",
    gender: "female",
    birthday: "29.05.2000",
    age: 24,
    position: "HR Manager",
    role: "Junior",
  },
  {
    name: "Nikita Morozov",
    email: "nikita.morozov@example.com",
    gender: "male",
    birthday: "14.03.1994",
    age: 30,
    position: "Project Manager",
    role: "Senior",
  },
  {
    name: "Elena Frolova",
    email: "elena.frolova@example.com",
    gender: "female",
    birthday: "06.06.1999",
    age: 25,
    position: "Business Analyst",
    role: "Middle",
  },
  {
    name: "Kirill Orlov",
    email: "kirill.orlov@example.com",
    gender: "male",
    birthday: "09.12.1998",
    age: 26,
    position: "Data Scientist",
    role: "Junior",
  },
  {
    name: "Polina Kuznetsova",
    email: "polina.kz@example.com",
    gender: "female",
    birthday: "23.07.2003",
    age: 21,
    position: "UI Designer",
    role: "Junior",
  },
  {
    name: "Roman Zaitsev",
    email: "roman.zaitsev@example.com",
    gender: "male",
    birthday: "04.08.1993",
    age: 31,
    position: "Security Specialist",
    role: "Senior",
  },
  {
    name: "Alina Smirnova",
    email: "alina.sm@example.com",
    gender: "female",
    birthday: "12.02.2002",
    age: 22,
    position: "Marketing Manager",
    role: "Middle",
  },
  {
    name: "Vladislav Denisov",
    email: "vlad.denisov@example.com",
    gender: "male",
    birthday: "15.05.2000",
    age: 24,
    position: "Mobile Developer",
    role: "Junior",
  },
  {
    name: "Daria Melnik",
    email: "daria.melnik@example.com",
    gender: "female",
    birthday: "30.11.1996",
    age: 28,
    position: "Content Manager",
    role: "Middle",
  },
  {
    name: "Alexey Kruglov",
    email: "alex.kruglov@example.com",
    gender: "male",
    birthday: "07.01.1992",
    age: 32,
    position: "CTO",
    role: "Senior",
  },
  {
    name: "Ksenia Loginova",
    email: "ksenia.log@example.com",
    gender: "female",
    birthday: "20.09.2001",
    age: 23,
    position: "UI/UX Designer",
    role: "Middle",
  },
  {
    name: "Egor Fadeev",
    email: "egor.fadeev@example.com",
    gender: "male",
    birthday: "19.04.2004",
    age: 20,
    position: "Intern Developer",
    role: "Junior",
  },
//   {
//     name: "Irina Petrova",
//     email: "irina.petrova@example.com",
//     gender: "female",
//     birthday: "02.03.1998",
//     age: 26,
//     position: "Recruiter",
//     role: "Middle",
//   },
//   {
//     name: "Timur Yakovlev",
//     email: "timur.yakovlev@example.com",
//     gender: "male",
//     birthday: "01.10.1997",
//     age: 27,
//     position: "Backend Developer",
//     role: "Middle",
//   },
//   {
//     name: "Natalia Egorova",
//     email: "natalia.egorova@example.com",
//     gender: "female",
//     birthday: "18.12.1995",
//     age: 29,
//     position: "Product Owner",
//     role: "Senior",
//   },
//   {
//     name: "Sergey Vinokurov",
//     email: "sergey.vinokurov@example.com",
//     gender: "male",
//     birthday: "24.05.1999",
//     age: 25,
//     position: "QA Engineer",
//     role: "Junior",
//   },
//   {
//     name: "Victoria Chernenko",
//     email: "victoria.chern@example.com",
//     gender: "female",
//     birthday: "09.09.2000",
//     age: 24,
//     position: "SMM Manager",
//     role: "Middle",
//   },
//   {
//     name: "Oleg Borisov",
//     email: "oleg.borisov@example.com",
//     gender: "male",
//     birthday: "13.06.1993",
//     age: 31,
//     position: "Tech Lead",
//     role: "Senior",
//   },
//   {
//     name: "Zlata Orlova",
//     email: "zlata.orlova@example.com",
//     gender: "female",
//     birthday: "22.08.2002",
//     age: 22,
//     position: "HR Assistant",
//     role: "Junior",
//   },
//   {
//     name: "Pavel Matveev",
//     email: "p.matveev@example.com",
//     gender: "male",
//     birthday: "16.04.1996",
//     age: 28,
//     position: "System Administrator",
//     role: "Middle",
//   },
//   {
//     name: "Yulia Denisova",
//     email: "yulia.denisova@example.com",
//     gender: "female",
//     birthday: "05.11.1997",
//     age: 27,
//     position: "UX Researcher",
//     role: "Middle",
//   },
];
